name: Publish Release assets

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-2019
    name: windows-2019 x64

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - run: echo "KIWI_VERSION=$(Get-Content .\.kiwiversion)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    - uses: robinraju/release-downloader@v1.2
      with:
        repository: "bab2min/Kiwi"
        tag: ${{ env.KIWI_VERSION }}
        fileName: "kiwi_model_${{ env.KIWI_VERSION }}_base.tgz"
    - uses: robinraju/release-downloader@v1.2
      with:
        repository: "bab2min/Kiwi"
        tag: ${{ env.KIWI_VERSION }}
        fileName: "kiwi_win_Win32_${{ env.KIWI_VERSION }}.zip"
    - uses: robinraju/release-downloader@v1.2
      with:
        repository: "bab2min/Kiwi"
        tag: ${{ env.KIWI_VERSION }}
        fileName: "kiwi_win_x64_${{ env.KIWI_VERSION }}.zip"
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Build
      run: |
        MSBuild.exe .\KiwiGui.csproj /p:Configuration=Release
    - name: Archive
      run: |
        mkdir KiwiGui_Windows
        mkdir KiwiGui_Windows\model
        mkdir KiwiGui_Windows\bin_x86
        mkdir KiwiGui_Windows\bin_x64
        mv bin\Release\*.exe KiwiGui_Windows\
        mv bin\Release\*.dll KiwiGui_Windows\
        Expand-Archive kiwi_win_Win32_${{ env.KIWI_VERSION }}.zip -DestinationPath x86
        mv x86\lib\kiwi.dll KiwiGui_Windows\bin_x86\
        Expand-Archive kiwi_win_x64_${{ env.KIWI_VERSION }}.zip -DestinationPath x64
        mv x64\lib\kiwi.dll KiwiGui_Windows\bin_x64\
        tar -zxvf kiwi_model_${{ env.KIWI_VERSION }}_base.tgz
        mv models/base/* KiwiGui_Windows\model\
        Compress-Archive -Path 'KiwiGui_Windows' -DestinationPath asset.zip
    - name: Upload release binary
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: asset.zip
        asset_name: kiwigui_win_${{ steps.get_release.outputs.tag_name }}.zip
        asset_content_type: application/octet-stream
